### PR TITLE
Improved home

### LINKED ISSUE #41: Whim should try to create its homedir if it doesn't exist

### LINKED ISSUE #42: Fix the WHIM_HOME env var check
Currently, Whim checks for $ENV{WHIM_HOME} at startup, but doesn't treat it right -- if set, it will then set Whim's home to "$ENV{WHIM_HOME}/.whim", and this is not what we want.

### PR DESCRIPTION
**Pull request by jmacdotorg**
Various improvements to how Whim reckons its own homedir, including setting one up when it's absent, and tests for same.

This fixes #41 and fixes #42.

### CODE REVIEW

**Comment by jmacdotorg** [comment]
This fixes #41 and fixes #42.

**Comment by jmacdotorg** [comment]
@adherzog:

> Do you intend for Whim::Core to be used apart from the Mojolicious app?

Good question. I think it should be available for invocation & use outside the app, for those who know what they're doing... and thus worth documenting someday. Why do you ask?

> Calling $self->whim->home in order to create the directory feels fragile and unnecessary. Likewise, having the home attribute of Whim::Core build a default that doesn't use the same default as Whim also feels like it'll lead to confusion at some point.

> I'd suggest making the home attribute a required, non-lazy attribute, with no default. The trigger should run on object construction, which will build the required directories. That'd solve both of the above issues.

This comes down on one side of something I felt undecided about, so I have acted as directed.

> It seems a bit weird the way author_photo_directory will attempt to create the directory, which will probably happen when you call $self->author_photo_directory->mkpath in _make_homedir. Is the intention that a user might want to set author_photo_directory to a path separate from the default in the whim home directory? If so, I'd handle it the same way home is handled - a required, non-lazy attribute with it's own trigger.

No, I don't intend that people would set these sub-directories separately. I've simplified the checks for them accordingly.

> In the test file, you're using both Mojo::File and Path::Tiny. It isn't clear which path() is actually being used. I suspect the Mojo::File usage can be dropped?

Cleaned up.

> I think my use case would probably be to create a new directory for my whim home, and then set WHIM_HOME accordingly. If I'm reading _make_homedir correctly, it won't make the subdirectories if the home directory already exists, which would be a failure in my use case. It should check each required directory for existence.

Oops missed this paragraph until just now. Lemme take a further look at this.

**Comment by adherzog** [comment]
@jmacdotorg 

> > Do you intend for Whim::Core to be used apart from the Mojolicious app?
> 
> Good question. I think it should be available for invocation & use outside the app, for those who know what they're doing... and thus worth documenting someday. Why do you ask?

It helps me understand how cleanly we should be separating concerns between Whim and Whim::Core.

For example, Whim::Core creates a 'log' directory, but IIUC, that directory only exists for use by Whim.

If you want Whim::Core to someday be a stand-alone module, I'd have that directory created in Whim.pm instead. On the other hand, if Whim::Core is thought of as just the engine of Whim, then it's fine as it is.

The latter case doesn't prevent a knowledgable user from using Whim::Core in some other way, of course. It just means it might do extra stuff, like creating a 'log' directory it doesn't need or use.

**Comment by jmacdotorg** [comment]
I've addressed the "WHIM_HOME is set and partially-but-not-completely exists on filesystem" use-case, so this is ready for re-review.

**Comment by adherzog** [comment]
@jmacdotorg Oh, I just looked back at #41, which this PR addresses. There are directories mentioned in that issue that aren't included here. Not sure if that was intentional or not.

**Comment by jmacdotorg** [comment]
Yeah, just `templates/`, right? Was also wobbly on that; not gonna fret about it for now, since (unlike `log/`) if it's missing the app will still work in a fully-functional way.

**Pull request merged**
